### ISSUE TITLE
旧版flomo停用的话怎么办呢

### ISSUE THREAD

**Issue by yoghurtdewdew** [seyeeL/sync-flomo-plugin#1]
今天登上去旧版的网页，自动跳转到了这个页面 https://help.flomoapp.com/community/update-new-version.html ，上面写着旧版停用…

<img width="815" alt="image" src="https://github.com/seyeeL/sync-flomo-plugin/assets/63794438/80e41927-4f99-4216-9900-96dad37c1d07">

我在网页端看了下，竟然没有回到旧版的链接了😂

<img width="234" alt="image" src="https://github.com/seyeeL/sync-flomo-plugin/assets/63794438/5d1a928d-6549-4233-8a87-86880a3f169a">

**Comment by seyeeL** [comment]
用不了了

**Comment by yoghurtdewdew** [comment]
我把之前放到Logseq的参数放到这里面，目前vsc里报错`/bin/sh: node: command not found`，按照网上的一些步骤操作了下，暂时没有解决这个问题😂 可能是我缺什么环境参数

**Comment by seyeeL** [comment]
不用研究了用不了了，flomo都把这些接口关掉了安装好了也没用
